# Generated by Django 5.1.1 on 2024-09-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
